/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 기본설정
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // 특정 폴더 > 카테고리
  feGroups: [
    {
      type: "autogenerated",
      dirName: "g-fe-docs",
    },
  ],
  beGroups: [
    {
      type: "autogenerated",
      dirName: "g-be-docs",
    },
  ],
  // But you can create a sidebar manually
};

export default sidebars;
